
version: "3.9"

name: ghaction
services:
  app:
    container_name: app_container
    build: . # relative path to Dockerfile
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/src/node_modules
    ports:
      - "3000:3000"
    tty: true
volumes:
  node_modules: